# permissions for end users to view customclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customcluster-viewer-role
rules:
- apiGroups:
  - hackathon.kaiyuanshe.cn
  resources:
  - customclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hackathon.kaiyuanshe.cn
  resources:
  - customclusters/status
  verbs:
  - get
