# permissions for end users to edit customclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customcluster-editor-role
rules:
- apiGroups:
  - hackathon.kaiyuanshe.cn
  resources:
  - customclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hackathon.kaiyuanshe.cn
  resources:
  - customclusters/status
  verbs:
  - get
