apiVersion: hackathon.kaiyuanshe.cn/v1
kind: Template
metadata:
  name: template-sample
  namespace: default
data:
  type: Pod
  podTemplate:
    image: coderhypo/ubunut-kylin:test-1
    command: [ "bash", "-c", "vncserver :1 -localhost no -geometry 1920x1080 -depth 24 && tail -F /home/ubuntukylin/.vnc/*.log" ]
    env:
      USER: ubuntukylin
  ingressProtocol: vnc
  ingressPort: 5901
  vnc:
    username: ubuntukylin
    password: ubuntukylin
