apiVersion: hackathon.kaiyuanshe.cn/v1
kind: Template
metadata:
  name: template-sample
  namespace: default
data:
  # Add fields here
  type: Pod
  podTemplate:
    image: busybox
    command:
      - "sh"
      - "-c"
      - "sleep 100000000"
